spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/acs}
    username: ${SPRING_DATASOURCE_USERNAME:acs}
    password: ${SPRING_DATASOURCE_PASSWORD:acs}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:/db/migration
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:}